server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://mysql:3306/userdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: kafka:9092